### ISSUE TITLE
What about RDB2RDF?

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-dir-literal#12]
2 more recommendations to add to the list ? 

https://www.w3.org/2001/sw/rdb2rdf/

**Comment by iherman** [comment]
There is a comment in the charter on r2rml; that is the name of the spec produced by the group. It is _probably_ to be added, but I should refresh my memory on how it works in case sql doesn't have the notion of direction. To be checked...

**Comment by pchampin** [comment]
> There is a comment in the charter on r2rml

Oops, sorry, I missed it.

Anyway, I think the answer is trivially "yes". Base direction for a column could be stored in another column of the same table (just like language).

Even if the direction is not stored in the RDB, external knowledge about its content could be added in the mapping to force the generated literals to have a given base direction.

**Comment by iherman** [comment]
You are right. I have added it in https://github.com/w3c/rdf-dir-literal/commit/89a8b8d76f3013ce913035d1057fcef7778a56a4

Closing the issue.
