### ISSUE TITLE
Scope of "editorial errata"

### ISSUE THREAD

**Issue by afs** [w3c/rdf-dir-literal#18]
> Editorial errata for the specifications will also be handled by the Working Group.

It is unclear whether this is limited to the area of focus of the proposed WG or to any editorial errata anywhere in any of the RDF 1.1 family of specifications mentioned.

If it is the latter, I hope that 
(1) this will be made clearer and more prominent
(2) it is contingent on access to wider expertise when outside the area of RDF literals.

There are two CG's looking at the whole area of the RDF 1.1 family of specifications and they are not mentioned in the charter.

In reality, one person's editorial change can be someone else's functional change.

**Comment by iherman** [comment]
Hey @afs, 

The intention is indeed to handle editorial errata for _all_ RDF 1.1 (or RDFa, etc) documents.

The [section on deliverables](https://w3c.github.io/rdf-dir-literal/draft-charter.html#deliverables) lists the official errata for each document family which, is, for RDF 1.1, is [the corresponding wiki page](https://www.w3.org/2001/sw/wiki/RDF1.1_Errata). I am not sure picking one or several CG-s that consider errata would be appropriate (we may forget others); what really counts is the official errata list. And, obviously, in case of unclear errata report the group can/should contact the original errata authors (and possibly other experts) for a proper handling of a specific erratum.

Would the following change on the charter text work for you?

> Official _editorial_ errata for the specifications in the respective families of documents will also be handled by the Working Group (see the references to the official errata lists in the [section on deliverables](#deliverables)). In case of doubt, the original errata author(s), as well as appropriate experts, must be contacted to make sure that the changes are not technical.

**Comment by afs** [comment]
Better. It does leave the burden on the WG process.

If some people are interested in the errata and not the main focus of the WG, then they would be unlikely to join or follow discussions closely or even put people off joining.

Maybe a separate repo/mailing list so you can track these editorial changes without needing to check every issue for the focus of the WG (IIRC GH repo watching all issues or nominated specific ones unless W3C has installed a repo extension e.g. "watch label" ).

**Comment by iherman** [comment]
Having a separate repo/mailing list to track the outsiders' comments or not is something that WG will have to decide if and when it is set up. 

I have labeled this issue to act on the charter text. I propose, however, to leave this issue open even after having made the changes, to have a reference to these additional actions later.

**Comment by iherman** [comment]
Closing via #20
