### ISSUE TITLE
direction agnostic querying

### ISSUE THREAD

**Issue by joernhees** [w3c/rdf-dir-literal#19]
somewhat related to the discussions in https://github.com/w3c/sparql-12/issues/34 i can see the need arising for querying in a dir-agnostic way, so cases where i want to match literals but ignore the direction.

e.g., what if i'd like to get all triples `?s ?p "hello world"@en^*`, so everything that is connected to a`"hello world"@en` no matter which direction (if at all)?

**Comment by iherman** [comment]
+1 to that. Probably a similar change would be needed for SHACL.

I wonder whether this is something to be added to charter. The current text says, in the scope:

> This Working Group will update the RDF 1.1 family of specification (including the serializations syntaxes), as well as a number of other, related specifications to include a base direction information for the langString datatype (see a detailed list of specifications below). 

Maybe it should say "adapt" the related specifications to make it clear that it is not only a matter of adding an updated reference but may require some thoughts like these. WDYT?

**Comment by iherman** [comment]
closed via #20
